# Generated by Django 4.2.1 on 2023-05-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_review_author_book_composite_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'can read all books')]},
        ),
    ]
